### ISSUE TITLE
[Issue]: Can't get to seek when in landscape mode

### ISSUE THREAD

**Issue by mobihen** [jellyflix-app/jellyflix#112]
![IMG_5119](https://github.com/user-attachments/assets/b96b5658-81a8-4798-ac94-17639704da3a)
### Please describe your bug

When viewing on my iPhone 14 Pro Max, 
I turn the phone to landscape and the seek bar is too close to the bottom making it impossible to seek as my finger catches the home button instead of the seek handle. 
Also, it seems that the other top buttons above the seed bar are too close to the seek handle making it also harder to seek

### Jellyflix Version

Other

### if other:

1.2.00156(64)

### Jellyfin Version

10.9.x

### Environment

```markdown
- OS:iOS
- OS Version:17.5.1
- Playback Method:Transcode
```

**Comment by jdk-21** [comment]
Hi @mobihen,
please check out this branch: https://github.com/jellyflix-app/jellyflix/tree/player-improved-margins
Does it improve the experience on your end?

**Comment by mobihen** [comment]
Thanks, I will check as within the next few days and update! :)

**Comment by mobihen** [comment]
@jdk-21 
getting error:
Failed to build iOS app
Could not build the precompiled application for the device.
Error (Xcode): lib/models/download_metadata.dart:177:3: Error: Type
'BaseItemDtoCurrentProgram' not found.

**Comment by jdk-21** [comment]
Did you update the tentacle api? Can you please check in the pubspec.lock that you still use the old tentacle version:
resolved-ref: "9baf9218fde0b78f401f64ca00398d787d1d2c91"
The new version has some api changes that Jellyflix doesn't use yet.

**Comment by mobihen** [comment]
@jdk-21 
YES! this is great! you should apply those changes to the main app
