### ISSUE TITLE
Support HarmonyOS

### ISSUE THREAD

**Issue by shanyan-wcx** [jellyflix-app/jellyflix#122]
This is Flutter for HarmonyOS: https://gitee.com/openharmony-sig/flutter_flutter

**Comment by jdk-21** [comment]
Thank you for the suggestion, but I don't think that this should be part of the official distribution. You can however compile a build yourself and I'm happy to link to your build from the readme.

**Comment by shanyan-wcx** [comment]
I have no understanding of Flutter at all. I tried to build it and got a lot of errors.

**Comment by jdk-21** [comment]
Can you outline the steps you took. I can't help you with this vague description.
