### ISSUE TITLE
[Issue]: Version number inside the app

### ISSUE THREAD

**Issue by enter-a-random-username** [jellyflix-app/jellyflix#131]
### Please describe your bug

Add it  1.20.0-preview... and about page has only license info. Would be nice to have an output for reports Android version + App version. Latest release is 0.10.0 - confused

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:
- OS Version:
- Playback Method:
```

**Comment by jdk-21** [comment]
97db169babe5ad6bbdfb37691e7fe7d2319ffa33 adds this
