### ISSUE TITLE
[Issue]: Downloads don't work on Windows

### ISSUE THREAD

**Issue by Snuupy** [jellyflix-app/jellyflix#133]
### Please describe your bug

transcoded downloads (or any downloads) don't work on Windows. I tried Win11, @sevenrats tried Win10, both don't work. I tried both jellyflix 1.3.1-preview0190 and 1.0.0-preview0113, same result on both. Download screen is blank after watching wifi traffic do things at ~300mbps for several minutes.

as per https://matrix-client.matrix.org/_matrix/media/v3/download/matrix.org/FKRFknrnwXWVcfSSuLoKesRR?allow_redirect=true

### Jellyflix Version

Other

### if other:

1.3.1-preview0190

### Jellyfin Version

10.9.x

### Environment

```markdown
- OS: Windows
- OS Version: Windows 11
- Playback Method: Download/Transcode
```

**Comment by sevenrats** [comment]
verified.

**Comment by schnellecom** [comment]
I am experiencing the same issue, also Windows 11 and Version 1.3.1-preview0190
