### ISSUE TITLE
[Issue]: when putting something into the watchlist it creates a public playlist

### ISSUE THREAD

**Issue by Aydanill** [jellyflix-app/jellyflix#136]
### Please describe your bug

Whenever you add anything to your wathclist, jellyfin makes it a public playlist

### Jellyflix Version

0.10.x

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Android, IOS
- OS Version: Android 14, IOS 16,17,18 beta
```

**Comment by jdk-21** [comment]
New Watchlist are now private. Existing watchlist playlists will still be public.
e370982af81c7abc461cd496cdac48d9d1970ce7
