### ISSUE TITLE
[Feature] Add support for Intro Skipper

### ISSUE THREAD

**Issue by OnismIS** [jellyflix-app/jellyflix#143]
Add support for Intro Skip button using [jumoog/Intro-Skipper](https://github.com/jumoog/intro-skipper) plugin

**Comment by jdk-21** [comment]
I want to allow 3rd party integrations into Jellyflix, but they need to follow some guidelines: #80 
But first we should implement the new media-segments feature that was introduced with 10.10.0. That way we wouldn't even need a 3rd party integration in Jellyflix itself. That way Intro-Skipping plugins could just add the correct media segments and you would still have the same benefits.

**Comment by OnismIS** [comment]
Got it, thank you.
