### ISSUE TITLE
[Issue]: No show downloads on Windows 11

### ISSUE THREAD

**Issue by manoloGith** [jellyflix-app/jellyflix#146]
### Please describe your bug

In Windows 11, when you download something to watch offline, it is not show in the downloads menu, but it is downloaded in ..Documents\jellyflix\downloads\1e7302.... video and other files 

Jellyflix version 1.3.1-preview0190

### Jellyflix Version

0.9.13

### if other:

1.3.1-preview0190

### Jellyfin Version

10.9.x

### Environment

```markdown
- OS: Windows
- OS Version:11
- Playback Method:
```

**Comment by jdk-21** [comment]
Had to check the issue first. There's already a fix in main and it will be available in the next release.

**Comment by manoloGith** [comment]
I'm waiting for it. Thank you.
