### ISSUE TITLE
Transcoded downloads

### ISSUE THREAD

**Issue by jdk-21** [jellyflix-app/jellyflix#3]
Implement a basic download functionality. Jellyflix will only be able to download the original files as Jellyfin doesn't support transcoded downloads yet.

**Comment by jdk-21** [comment]
It seems that transcoded downloads are actually possible.

- [x] Download button and download with fixed bitrate
- [x] Download Screen
- [x] Offline Player Screen
- [ ] Show download progress
- [ ] Save Additional metadata for Download Screen
- [ ] Background download (iOS, Android)
- [ ] Verify download
- [ ] Resume download
- [ ] Remove download
- [ ] Offline mode

**Comment by sevenrats** [comment]
there is some chatter about implementing a new controller for this purpose.  in the meantime nothing stops a client from requesting whatever transcode they want and then just dumping the bytes to disk.  the only drawback is the baked-in decisions that are made in the transcoding controller that make tradeoffs in favor of speed.  thus, the new controller will make configurable tradeoffs, or tradeoffs in terms of quality. but there is nothing flatly stopping this from being implemented.

**Comment by jdk-21** [comment]
Downloads are in the latest prerelease. I'm leaving this issue open for any additional work on this feature until it's in stable.
