### ISSUE TITLE
[Issue]: Login on macOS isn't working

### ISSUE THREAD

**Issue by jdk-21** [jellyflix-app/jellyflix#40]
### Please describe your bug

Currently the login on the macOS-Version (.dmg) isn't working on macOS. After notarization the app can't access the Keychain and therefore can't read or write the login credentials.

Workaround: You can download the iOS App from the App Store. It has the same functionality and look as the .dmg-version.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: macOS
- OS Version: Probably every supported macOS version
```

**Comment by sevenrats** [comment]
we should be able to make this work by using the user keychain, not the system one.

**Comment by jdk-21** [comment]
The latest pre-release should fix this issue. We are now using encrypted Hive boxes. Maybe the issue gets completly resolved on the package side (flutter_secure_storage).

@sevenrats If you have any further insights on this issue, let me know. The issue only occurs after notarizing the app. In debug and and release mode everythings works fine.
