### ISSUE TITLE
[Issue]: Images don't show when using demo server.

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#45]
### Please describe your bug

I log in using your live demo to the Jellyfin teams official demo server. I expect to see images but I do not see them.

### Jellyflix Version

Other

### if other:

whatever the live demo is

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Debian
- OS Version: bookworm
- Playback Method: web, unknown because it failed
```

**Comment by jdk-21** [comment]
Sorry, but I can't reproduce your issue. Could you send some screenshot and lay out the steps you took?
In rare occasions the images don't load because of connection related stuff, but I probably can't do much about that.

**Comment by sevenrats** [comment]
i can reproduce it on a modern develop version either.
