### ISSUE TITLE
[Issue]:  Playback fails

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#49]
### Please describe your bug

Tested on both Ubuntu 22 and debian bookworm, chrome and firefox.  Playback never happens when using the demo server, trying several different titles.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: debuntu stable
- OS Version: 22/bookworm respectively
- Playback Method: im not actually sure it didnt work, so.
```

**Comment by sevenrats** [comment]
I have reproduced this issue on my personal server with the linux build and this error repeats every second or so in the console:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Invalid radix-10 number (at character 1)
auto
^

#0      int._handleFormatError (dart:core-patch/integers_patch.dart:126)
#1      int._parseRadix (dart:core-patch/integers_patch.dart:137)
#2      int._parse (dart:core-patch/integers_patch.dart:98)
#3      int.parse (dart:core-patch/integers_patch.dart:60)
#4      _PlayerSreenState.initState.<anonymous closure>.<anonymous closure> (package:jellyflix/screens/player_screen.dart:93)
#5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398)
#6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429)
#7      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
```

**Comment by sevenrats** [comment]
ok i was able to get further by upgrading my OS to debian trixie.

on develop branch, the app is clearly failing because its trying to open the wrong url some how.  the console clearly shows the app failing to open a transcode due to unsupported subtitles, but then the server begins a direct stream (so its not surprising the transcode url fails, when the server thinks there is no transcode)

**Comment by jdk-21** [comment]
Are you referring to the Linux client? Can you please share the metadata of the file you are trying to play. I only added the most common subtitles to direct stream right now. So this could be an issue.

**Comment by sevenrats** [comment]
i will dive back into this today. the changes in my linked PR "fix" it, but I have not yet produced a successful transcode, only succesful directplay.

**Comment by sevenrats** [comment]
can't reproduce this issue outside my environment on a modern dev version.  If you are having this issue, please follow the mpv symlink workaround in the docs.
