### ISSUE TITLE
[Issue]: No evidence that playback has failed when it has failed

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#51]
### Please describe your bug

When playback fails due to some bug, there is no indication to the user. the spinner just keeps on spinning.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: debian
- OS Version: trixie
- Playback Method: server thinks direct but jellyflix thinks transcode (doesnt work)
```

**Comment by jdk-21** [comment]
There is now an alert message, if there is a stream error.
