### ISSUE TITLE
[Issue]: Website no longer loads at all

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#52]
### Please describe your bug

https://jellyflix.kiejon.com/ is just a blank white screen
confirmed from multiple parts of the world.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:
- OS Version:
- Playback Method:
```

**Comment by jdk-21** [comment]
`dart:io` slipped through. This package is not supported on Flutter web. That's why it isn't loading anymore. My IDE always adds it automatically instead of universal_io.
This will be fixed in the next preview release.
