### ISSUE TITLE
[Feature Request]: Chat space 

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#56]
### Please describe your bug

Could we get a discord or matrix server going to talk about this app?

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS:
- OS Version:
- Playback Method:
```

**Comment by jdk-21** [comment]
We already have a matrix chat (see first link in the readme). And Github discussions is also activated for async conversations.
But I understand that only having a chat can be challenging, that's why I created a Matrix space for Jellyflix. The new link is already in the development branch.
