### ISSUE TITLE
[Issue]: In the Library Screen, episodes are named with the episode title.

### ISSUE THREAD

**Issue by marvintnk** [jellyflix-app/jellyflix#58]
### Please describe your bug

Problem:

In the Library Screen, episodes are named with the episode title.

Issues with this behavior:

The Library Screen becomes cluttered with numerous episodes, making it difficult to get an overview of relevant movies, for instance.
Episode titles cannot be associated with their respective series, which becomes irrelevant when searching for media.
Proposed Solution:

Group episodes by series and only list them in the Library Screen.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: IOS
- OS Version: IOS 17.04
```

**Comment by jdk-21** [comment]
Yes, we should probably change that for the next release.
