### ISSUE TITLE
[Issue]: Pressing enter on the login screen does not activate the button

### ISSUE THREAD

**Issue by sevenrats** [jellyflix-app/jellyflix#63]
### Please describe your bug

pressing enter should activate the ontap function

**Comment by opioom** [comment]
I have the same issue with my mac. Mac OS Ventura 13.5.1, i9, 32GB Ram. Can't login after installation. Check all versions of Jellyflix available for mac and none of this works. After server address with http:// and :portnumber, user and correct password the Login button is blue but has no reaction when click. The same with Enter. No reaction. Nothing is happening. No way to even test the app.

**Comment by sevenrats** [comment]
@opioom this issue report is for a superficial UX issue wherein the login button is not the "enter" focus for the text box.  If you are unable to login at all, even by clicking, that warrants a new issue report.

**Comment by jdk-21** [comment]
@opioom Please use the prerelease version, if you're not already using it.

**Comment by opioom** [comment]
> @opioom Please use the prerelease version, if you're not already using it.

I checked all Mac versions. None of them works. No way to login. No reaction.

**Comment by sevenrats** [comment]
@opioom This issue report is not about what you are experiencing. Open a new issue report. This one is about to be closed by #124
