### ISSUE TITLE
[Feature]: Option to use posters instead of backdrops in Continue Watching Section

### ISSUE THREAD

**Issue by simoncaron** [jellyflix-app/jellyflix#78]
Currently, the "Continue Watching" section of the home screen is using backdrops for each item. This can lead to weird results:

![image](https://github.com/jellyflix-app/jellyflix/assets/8635747/9b842901-3985-4748-b0d6-a1a2b474131a)

It would be nice if the option to select posters instead of backdrops for this section was offered to the user.

**Comment by jdk-21** [comment]
Ah yes, we should change that. The only problem is that episodes normally don't have posters. So it would only improve it for movies. But maybe there is also a solution for episodes.

**Comment by simoncaron** [comment]
The Jellyfin Web UI has this option: 

![image](https://github.com/jellyflix-app/jellyflix/assets/8635747/9dbaa391-7147-4437-adda-3f5bfb2f52e8)

So for shows, you can either have the episode tumbnail or the show main artwork.

**Comment by simoncaron** [comment]
For shows it could be the main series artwork, for movies the main poster maybe?

**Comment by jdk-21** [comment]
I like the solution of the web ui with optional covers. I think the default should then be movie and series posters. And in the settings you can still enable backdrop for episodes.
