### ISSUE TITLE
[Issue]: unable to connect my jellyfin server  https://jellyfin.mydomain.com

### ISSUE THREAD

**Issue by priyajit4u** [jellyflix-app/jellyflix#84]
### Please describe your bug

I am operating a jellyfin server however jellyflix is unable to connect to it although other jellyfin client is able to.

### Jellyflix Version

0.10.x

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: Mac OS Monetary
- OS Version: 12.5.1
- Playback Method: Transcode
```

**Comment by jdk-21** [comment]
Hi @priyajit4u. Do you use a self-signed certificate? Jellyflix automatically tests for port 8096, so you might need to specify the correct port. And can you connect to https://demo.jellyfin.org/stable?

**Comment by jdk-21** [comment]
I've noticed that you use macOS. Please use the latest prerelease from the Releases Page. Or you can download the App from the App Store.

**Comment by priyajit4u** [comment]
Yeah...after using the pre-release version issue is fixed...thank you very
much and keep up the good work...I am loving jellyflix

**Comment by jdk-21** [comment]
Thank you 👍
