### ISSUE TITLE
[Issue]: NavBar Items Overflow for some languages

### ISSUE THREAD

**Issue by simoncaron** [jellyflix-app/jellyflix#86]
### Please describe your bug

On devices where the navbar is permanently displayed on the left of the app (tablets, PC), the items can sometimes overflow depending of the language used. In french, the Download item of the navbar, is overflowing:

![image](https://github.com/jellyflix-app/jellyflix/assets/8635747/49ff69ca-fb7d-4c40-9c23-a2c2441164ac)

Maybe something like [auto_size_text](https://pub.dev/documentation/auto_size_text/latest/) could be used... that would shrink the font of the items to fit the button size.

### Jellyflix Version

Other

### if other:

latest main

### Jellyfin Version

10.8.13

### Environment

```markdown
- OS: iOS/Linux
- OS Version: N/A
- Playback Method: N/A
```

**Comment by sevenrats** [comment]
if you have time to play with this i would look at the text overflow parameters.  iirc flutter offers "ellipsis" and "fade" and both can be used with or without line wrap. frankly we depend on non-english readers to tell us which combination of these is going to look better more often.

**Comment by jdk-21** [comment]
This kind a of a different problem. Normally we do have a way to extend the text in one direction or it isn't important to fully see the text. In this case you should be able to see the whole label even if you have to scale it down. Or we scale up the width of the navbar.
I assign you the issue, let me know if you need something.

**Comment by sevenrats** [comment]
I've given this some thought and I think we implement the solution in the form of contributor and/or style guidelines.  We should simply divine what our maximum string length reasonably is and force the user to use it.  It's a bit outside my wheelhouse but it would be neat if we could make the CI enforce it.  Then, if we encounter a situation where a contributor *just can't* make a particular string work, then and only then do we do the hard work of re-evaluating the layout code.

**Comment by sevenrats** [comment]
ok this has progressed in chat just a bit and I think we have established that the standard solution is just implementing TextOverflow.Ellipsis
No reason we need to make it more complicated than that.
