### ISSUE TITLE
[Issue]: How to download media for offline use?

### ISSUE THREAD

**Issue by funkyfunked** [jellyflix-app/jellyflix#99]
### Please describe your bug

Hello and thanks for your app! In the description is stated that a feature is to download media files, maybe even transcodes for offline use, I'm interrested! How do I use this feature? Can't find anything in the UI or ths readme.

Tested on android and win.

### Jellyflix Version

0.9.13

### Jellyfin Version

10.9.x

### Environment

```markdown
- OS:
- OS Version:
- Playback Method:
```

**Comment by jdk-21** [comment]
Download support is currently only available in the preview releases.  You can use Tesflight or download the latest preview release from the releases page on GitHub.
